-- AlterTable
ALTER TABLE `discharge` MODIFY `HOW_TO_USE_IT` ENUM('LINE_DISPENSING', 'DOT_DISPENSING', 'LINE_DISPENSING_OR_DOT_DISPENSING', 'MOLDING_FILLING_METERING_VALVE', 'UNDERFILLING', 'SEALING', 'CONFORMAL_COATING_SPRAYING_SPRAY_VALVE', 'EVERYTHING') NULL DEFAULT 'EVERYTHING';
