-- AlterTable
ALTER TABLE `application` MODIFY `SUPPLY_FORM` ENUM('BARREL_SYRINGE', 'CARTRIDGE', 'TANK', 'CAN_DRUM', 'TANK_OR_CAN_DRUM', 'EXCEPT_TANK_OR_CAN_DRUM', 'EVERYTHING') NULL DEFAULT 'EVERYTHING';

-- AlterTable
ALTER TABLE `discharge` MODIFY `SUPPLY_FORM` ENUM('BARREL_SYRINGE', 'CARTRIDGE', 'TANK', 'CAN_DRUM', 'TANK_OR_CAN_DRUM', 'EXCEPT_TANK_OR_CAN_DRUM', 'EVERYTHING') NULL DEFAULT 'EVERYTHING';

-- AlterTable
ALTER TABLE `supply` MODIFY `SUPPLY_FORM` ENUM('BARREL_SYRINGE', 'CARTRIDGE', 'TANK', 'CAN_DRUM', 'TANK_OR_CAN_DRUM', 'EXCEPT_TANK_OR_CAN_DRUM', 'EVERYTHING') NULL DEFAULT 'EVERYTHING';
